# Use an official Node.js runtime as a parent image
FROM node:14 as build-stage

# Set the working directory to /app
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the Angular app
RUN npm run build

# Use a lightweight Nginx image as the final image
FROM nginx:alpine

# Copy the built Angular app from the previous stage
COPY --from=build-stage /app/dist /usr/share/nginx/html

# Expose the port Nginx listens on (default is 80)
EXPOSE 80

# Command to start Nginx
CMD ["nginx", "-g", "daemon off;"]
