const demoFiles = [
    { name: "Alpha Report", type: "PDF", sizeKB: 1200 },
    { name: "Beta Analysis", type: "DOCX", sizeKB: 850 },
    { name: "Gamma Summary", type: "PPTX", sizeKB: 1600 },
    { name: "Delta Overview", type: "XLSX", sizeKB: 500 },
    { name: "Epsilon Notes", type: "TXT", sizeKB: 300 },
    { name: "Zeta Guide", type: "PDF", sizeKB: 1100 },
    { name: "Eta Reference", type: "DOCX", sizeKB: 950 },
    { name: "Theta Blueprint", type: "PDF", sizeKB: 1400 },
    { name: "Iota Manual", type: "TXT", sizeKB: 400 },
    { name: "Kappa Sketch", type: "PDF", sizeKB: 1250 },
    { name: "Lambda Draft", type: "DOCX", sizeKB: 600 },
    { name: "Mu Concept", type: "PPTX", sizeKB: 1700 },
    { name: "Nu Outline", type: "XLSX", sizeKB: 750 },
    { name: "Xi Plan", type: "PDF", sizeKB: 1300 },
    { name: "Omicron Projection", type: "DOCX", sizeKB: 900 },
    { name: "Pi Calculation", type: "XLSX", sizeKB: 650 },
    { name: "Rho Graph", type: "TXT", sizeKB: 350 },
    { name: "Sigma Survey", type: "PDF", sizeKB: 1200 },
    { name: "Tau Report", type: "DOCX", sizeKB: 800 },
    { name: "Upsilon Analysis", type: "PPTX", sizeKB: 1500 },
    { name: "Phi Overview", type: "XLSX", sizeKB: 550 },
    { name: "Chi Notes", type: "TXT", sizeKB: 320 },
    { name: "Psi Guide", type: "PDF", sizeKB: 1150 },
    { name: "Omega Reference", type: "DOCX", sizeKB: 920 },
    { name: "Eclipse Blueprint", type: "PDF", sizeKB: 1350 },
    { name: "Nebula Manual", type: "TXT", sizeKB: 410 },
    { name: "Galaxy Sketch", type: "PDF", sizeKB: 1280 },
    { name: "Quasar Draft", type: "DOCX", sizeKB: 630 },
    { name: "Pulsar Concept", type: "PPTX", sizeKB: 1650 },
    { name: "Starlight Outline", type: "XLSX", sizeKB: 780 }
  ];
  
  export default demoFiles;